#пути
train: "admin.jsonl"
labels: "labels.json"
output_file: "debug_model_checkpoints.json"
output_dir: "./debug_model_checkpoints"

#данные модели
model_name: "distilbert/distilbert-base-multilingual-cased"

#аргументы для модели
max_length_tok: 128
per_device_train_batch_size: 1
num_train_epochs: 10