#пути
train: "admin.jsonl"
labels: "labels.json"
output_file: "/Users/maksim/PycharmProjects/rezume_NER/modelPavel/pavel_labels.json"
output_dir: "/Users/maksim/PycharmProjects/rezume_NER/modelPavel/debug_model_checkpoints"

path_for_evalution: "admin3.jsonl"
labels_for_evaluation: "/modelPavel/pavel_labels.json"
#данные модели
model_name: "DeepPavlov/rubert-base-cased"

#аргументы для модели
max_length_tok: 128
per_device_train_batch_size: 1
num_train_epochs: 10